### ISSUE TITLE
Running make gives an error

### ISSUE THREAD

**Issue by ChthonicCrusader** [jessesung/hex2hcd#2]
Using RPi 3. When ran make command got following error message:

gcc -O2 -march=native    hex2hcd.c   -o hex2hcd
*** Error in `gcc': double free or corruption (top): 0x002a4c58 ***
<builtin>: recipe for target 'hex2hcd' failed
make: *** [hex2hcd] Aborted

**Comment by ChthonicCrusader** [comment]
Fix:
Replaced -march=native with -mcpu=cortex-a53 in Makefile so that CFLAGS looks lke:

CFLAGS  = -O2 -mcpu=cortex-a53
Source: Serverov's comment on https://github.com/Motion-Project/motion/issues/104
Close it if found genuine

**Comment by jessesung** [comment]
@ChthonicCrusader: I'm thinking about removing the whole optimization stuff since this is a quite small tool. Does it work for you with "CFLAGS = -O2"?

**Comment by benedictsuarez888** [comment]
Same problem. "Failed to open" is the error message.
